### PR TITLE
fixed the filename

### PR DESCRIPTION
**Pull request by jettero**
tamper monkey will automatically offer to install userscript from the raw url if you just end the file with .user.js

### CODE REVIEW

**Review by skehlet — CHANGES_REQUESTED** [review]
Hi! Thanks for the PR! Could you change the `@downloadURL` to point to my repo?

**Comment by jettero** [comment]
I thought I had done so.

**Comment by jettero** [comment]
Apparently, if you submit a pull request and then continue editing that branch, the pull request updates with the commits. I wasn't aware of that. Makes sense. I should have made a feature branch for this.

**Comment by skehlet** [comment]
Okay! Looking forward to a new PR. Thanks again.

**Comment by jettero** [comment]
I may not get to it. Time will tell. The script is definitely firing, but it's not actually changing the comment order for me. I mean to figure that out, but ... you know ... time.

**Comment by skehlet** [comment]
Bummer, I use it every day and am so glad for it. I had some trouble getting it to work across upgrades though, the sidebar was a problem.

**Pull request closed without merging**
